
name: CI

on: [pull_request, push]

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9

      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: '${{GITHUB_BASE_REF}}:schema.graphql'
