# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [pull_request, push]

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9

      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: '${{ github.base_ref }}:schema.graphql'
